---

- hosts: all
  become: true
  tasks:
    - name: install apace2 package
      package:
        name: apache2 
        state: latest
        update_cache: yes

    - name: copy default html file
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
